import Head from "next/head";
import HighLight from "./components/HighLight/index";
import Overview from "./components/Overview/index";
import AIML from "./components/AIML/index";
import RpaProcess from "./components/Process/index";
import Solutions from "./components/Solutions/index";
import CaseStudy from "./components/CaseStudy/index";
import Contact from "./components/Contact/index";
import styles from "./home.module.scss";
import { useEffect, useRef } from "react";
import { gsap } from "gsap";
import ScrollTrigger from "gsap/dist/ScrollTrigger";
import Link from "next/link";

export default function Home() {
  useEffect(() => {
    const handleScroll = (e) => {
    let firstElement = document.getElementById("highLight")
    let view = firstElement.getBoundingClientRect()
    let height = view.height

    // window.scrollBy({
    //   top: height ,
    //   left: 0,
    //   behavior: 'smooth'
    // });
    };
    window.addEventListener("scroll", handleScroll);

    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);

  return (
    <div>
      <Head>
        <title>RPA_TMA</title>
        <link rel="icon" href="/TmaLogo.svg" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
        <meta name="description" content="Generated by DC22" />
      </Head>
      <main>
        <div className={styles.container} id="wrap">
          <section className="panel highLight" id="highLight">
            <HighLight />
          </section>
          <section className="panel overview" id="overw">
            <Overview />
          </section>
          <section className="panel aiml">
            <AIML />
          </section>
          <section className="panel rpaProcess">
            <RpaProcess />
          </section>
          <section className="panel solutions">
            <Solutions />
          </section>
          <section className="panel caseStudy" id="case-study">
            <CaseStudy />
          </section>
          <section className="panel contact">
            <Contact />
          </section>
        </div>
      </main>

      <footer></footer>
    </div>
  );
}
