import Head from "next/head";
import { HighLight } from "./components/HighLight/index";
import { Overview } from "./components/Overview/index";
import { AIML } from "./components/AIML/index";
import { RpaProcess } from "./components/Process/index";
import { Solutions } from "./components/Solutions/index";
import { CaseStudy } from "./components/CaseStudy/index";
import { Contact } from "./components/Contact/index";
import styles from "./home.module.scss";

export default function Home() {
  return (
    <div>
      <Head>
        <title>RPA_TMA</title>
        <link rel="icon" href="/TmaLogo.png" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
        <meta name="description" content="Generated by DC22" />
      </Head>
      <main>
        <div className={styles.container}>
          <HighLight />
          {/* <Overview />
          <AIML />
          <RpaProcess />
          <Solutions />
          <CaseStudy />
          <Contact /> */}
        </div>
      </main>

      <footer></footer>
    </div>
  );
}
