import className from "classnames/bind";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import Overview from "../components/home/Overview";
import document from "../pages/_document";

const cx = className.bind(styles);
export default function Home() {
  return (
    <div>
      <Head>
        <title>RPA_TMA</title>
        <meta name="description" content="Generated by DC22" />
        <link rel="icon" href="/TMA-favicon.png" />
        <document />
      </Head>

      <main>
        <Overview />
      </main>

      <footer></footer>
    </div>
  );
}
