import className from "classnames/bind";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

const cx = className.bind(styles);
export default function Home() {
  return (
    <div>
      <Head>
        <title>RPA_TMA</title>
        <meta name="description" content="Generated by DC22" />
        <link rel="icon" href="/TMA-favicon.png" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>

      <footer></footer>
    </div>
  );
}
